# Generated by Django 4.2.1 on 2023-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_english', models.CharField(max_length=100, verbose_name='английское слово')),
                ('_russian', models.JSONField(verbose_name='русские слова')),
                ('_transcription', models.CharField(max_length=50, verbose_name='транскрипция')),
                ('_synonyms', models.ManyToManyField(blank=True, to='main.word', verbose_name='синонимы')),
            ],
        ),
    ]
